version: '3'
services:
    erp-web:
        image: nginx:alpine
        container_name: erp-web
        ports:
            - "8080:80"
        volumes:
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
            - .:/var/www
        depends_on:
           - erp-app
           - erp-mysql

    erp-app:
        image: luxury123456/erp-app
        container_name: erp-app
        working_dir: /var/www
        volumes:
            - .:/var/www
        ports:
            - "9000:9000"
        env_file:
            - ".env"
              #        command: bash -c "composer config -g github-oauth.github.com ${GITHUB_TOKEN}"

    erp-mysql:
        image: mysql:5.7
        container_name: ${DB_HOST}
        restart: always
        ports:
            - "3388:3306"
        volumes:
            - dbdata:/var/lib/mysql
        env_file:
            - ".env"
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}

    myadmin:
        image: phpmyadmin/phpmyadmin
        container_name: erp-phpmyadmin
        ports:
            - "8000:80"
        environment:
            - PMA_ARBITRARY=1
            - PMA_HOST=${DB_HOST}
        restart: always
        depends_on:
            - erp-mysql
volumes:
    dbdata:

